# Generated by Django 5.2.1 on 2025-05-31 21:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nom de la catégorie')),
                ('slug', models.SlugField(blank=True, help_text="Un identifiant unique pour l'URL, généré automatiquement si vide.", unique=True)),
                ('description', models.TextField(blank=True, verbose_name='Description de la catégorie')),
            ],
            options={
                'verbose_name': 'Catégorie',
                'verbose_name_plural': 'Catégories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nom du produit')),
                ('slug', models.SlugField(blank=True, help_text="Un identifiant unique pour l'URL du produit, généré automatiquement.", unique=True)),
                ('description', models.TextField(verbose_name='Description du produit')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prix (FCFA)')),
                ('stock', models.PositiveIntegerField(default=0, verbose_name='Quantité en stock')),
                ('main_image', models.ImageField(blank=True, null=True, upload_to='products/main_images/', verbose_name='Image principale')),
                ('is_available', models.BooleanField(default=True, verbose_name='Disponible à la vente')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de dernière modification')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='boutiques.category', verbose_name='Catégorie')),
            ],
            options={
                'verbose_name': 'Produit',
                'verbose_name_plural': 'Produits',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/gallery_images/', verbose_name='Fichier image')),
                ('alt_text', models.CharField(blank=True, max_length=255, verbose_name='Texte alternatif (pour SEO et accessibilité)')),
                ('order', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='boutiques.product', verbose_name='Produit')),
            ],
            options={
                'verbose_name': 'Image de produit',
                'verbose_name_plural': 'Images de produits',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ProductVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_file', models.FileField(blank=True, null=True, upload_to='products/videos/', verbose_name='Fichier vidéo (hébergé)')),
                ('video_url', models.URLField(blank=True, null=True, verbose_name='URL vidéo (YouTube/Vimeo)')),
                ('caption', models.CharField(blank=True, max_length=255, verbose_name='Légende de la vidéo')),
                ('order', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='boutiques.product', verbose_name='Produit')),
            ],
            options={
                'verbose_name': 'Vidéo de produit',
                'verbose_name_plural': 'Vidéos de produits',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Nom de la boutique')),
                ('slug', models.SlugField(blank=True, help_text="Un identifiant unique pour l'URL de la boutique, généré automatiquement.", unique=True)),
                ('description', models.TextField(blank=True, verbose_name='Description de la boutique')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='shops/logos/', verbose_name='Logo de la boutique')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de dernière modification')),
                ('is_active', models.BooleanField(default=True, verbose_name='Boutique active')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shops', to=settings.AUTH_USER_MODEL, verbose_name='Propriétaire')),
            ],
            options={
                'verbose_name': 'Boutique',
                'verbose_name_plural': 'Boutiques',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='boutiques.shop', verbose_name='Boutique'),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('is_seller', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
