# Generated by Django 5.2.1 on 2025-05-31 21:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boutiques', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Prix total de la commande')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('processing', 'En traitement'), ('shipped', 'Expédiée'), ('delivered', 'Livrée'), ('cancelled', 'Annulée')], default='pending', max_length=20, verbose_name='Statut de la commande')),
                ('shipping_address_line1', models.CharField(blank=True, max_length=255, null=True, verbose_name='Adresse ligne 1')),
                ('shipping_address_line2', models.CharField(blank=True, max_length=255, null=True, verbose_name='Adresse ligne 2')),
                ('shipping_city', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ville')),
                ('shipping_country', models.CharField(blank=True, max_length=100, null=True, verbose_name='Pays')),
                ('shipping_postal_code', models.CharField(blank=True, max_length=20, null=True, verbose_name='Code postal')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de commande')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière mise à jour')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='Client')),
            ],
            options={
                'verbose_name': 'Commande',
                'verbose_name_plural': 'Commandes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255, verbose_name="Nom du produit (au moment de l'achat)")),
                ('price_at_purchase', models.DecimalField(decimal_places=2, max_digits=10, verbose_name="Prix unitaire (au moment de l'achat)")),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Quantité')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='boutiques.order', verbose_name='Commande')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='boutiques.product', verbose_name='Produit')),
            ],
            options={
                'verbose_name': 'Article de commande',
                'verbose_name_plural': 'Articles de commandes',
            },
        ),
    ]
