# Generated by Django 5.2.1 on 2025-05-31 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boutiques', '0003_review'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'Profil Utilisateur', 'verbose_name_plural': 'Profils Utilisateurs'},
        ),
        migrations.AddField(
            model_name='userprofile',
            name='postal_code',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Code postal'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='order',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name="Ordre d'affichage"),
        ),
        migrations.AlterField(
            model_name='productvideo',
            name='order',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name="Ordre d'affichage"),
        ),
    ]
