"""
Django settings for marketplace_project project.

Generated by 'django-admin startproject' using Django 4.2.20.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv

load_dotenv() # charge les variables du fichier .env


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# Use an environment variable for SECRET_KEY in production!
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY', 'django-insecure-1-hami7&3^wjwcio&*za^i86vp2h^9qo)gx_0+*33!)mdmoc@1')
# For development, you can use the hardcoded string above.
# For production, set DJANGO_SECRET_KEY as an environment variable (e.g., in your server config).

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True # Set to False in production

# Allowed hosts for your Django application
# In production, this should be your domain name (e.g., 'www.yourmarketplace.com', 'yourmarketplace.com')
ALLOWED_HOSTS = ['*'] # Change this to your domain(s) in production, e.g., ['127.0.0.1', 'localhost', 'yourdomain.com']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
    'boutiques',
    'registration',
    'crispy_forms',
    'crispy_bootstrap5',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'marketplace_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'marketplace_project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2', # Changed to PostgreSQL
        'NAME': os.environ.get('DB_NAME', 'mon_marketplace_db'), # Use environment variable for name
        'USER': os.environ.get('DB_USER', 'mon_marketplace_user'), # Use environment variable for user
        'PASSWORD': os.environ.get('DB_PASSWORD', 'votre_mot_de_passe_fort'), # Use environment variable for password
        'HOST': os.environ.get('DB_HOST', 'localhost'), # Use environment variable for host
        'PORT': os.environ.get('DB_PORT', '5432'), # Use environment variable for port
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Crispy Forms configuration
CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap5"
CRISPY_TEMPLATE_PACK = "bootstrap5"


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'fr-fr' # Changed to French for Mali context

TIME_ZONE = 'Africa/Bamako' # Changed to Bamako timezone for Mali context

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'
# Define STATIC_ROOT for collecting static files in production
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')


# Configuration pour les fichiers médias (images, vidéos téléchargées)
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Login/Logout Redirect URLs
LOGIN_REDIRECT_URL = '/boutiques/vendeur/dashboard/' # A good default for a marketplace seller
LOGOUT_REDIRECT_URL = '/' # Redirect to homepage after logout

